name: label_creator
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - qrcode
  - tk
  - ipykernel
  - pandas
  - ca-certificates
  - openssl
  - requests
  - reportlab
  - pyinstaller
  - certifi
  - fuzzywuzzy
